<?xml version="1.0"?>
<robot name="m4w_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
<xacro:include filename="$(find mybot_description)/urdf/m4w_robot.gazebo" />

  <xacro:property name="base_width" value="0.16"/>
  <xacro:property name="base_len" value="0.2"/>
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="base_wheel_gap" value="0.007"/>
  <xacro:property name="wheel_separation" value="0.15"/>
  <xacro:property name="wheel_joint_offset" value="0.02"/>

  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}"/>
    </inertial>
  </xacro:macro>
 
  <link name="base_footprint">
    <xacro:box_inertia m="20" w="0.001" h="0.001" d="0.001"/>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
	<material name="green"/>
    </visual>
  </link>
 
  <link name="base_link">
    <xacro:box_inertia m="10" w="${base_len}" h="${base_width}" d="0.02"/>
    <visual>
      <geometry>
        <box size="${base_len} ${base_width} 0.02"/>
      </geometry>
<material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_len} ${base_width} 0.02"/>
      </geometry>
	
    </collision>
  </link>
   <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
    </inertial>
  </xacro:macro>
 
  <xacro:macro name="wheel" params="prefix reflect wheel_joint">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.01"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.01"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="10" r="${wheel_radius}" h="0.005"/>
    </link>
 
    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${wheel_joint} ${((base_width/2)+base_wheel_gap)*reflect} -0.005" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
 
  <xacro:wheel prefix="left" reflect="1" wheel_joint="0.08" />
  <xacro:wheel prefix="right" reflect="-1" wheel_joint="0.08"/>
  <xacro:wheel prefix="left_f" reflect="1" wheel_joint="-0.08" />
  <xacro:wheel prefix="right_f" reflect="-1" wheel_joint="-0.08"/>
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius + 0.005}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

</robot>
